# Generated by Django 2.0.4 on 2018-09-20 04:51

from django.db import migrations, models
import gestionfruta.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, default='', max_length=120)),
                ('telefono', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('departamento', models.CharField(max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=120, null=True)),
                ('imagen', models.ImageField(default='', null=True, upload_to=gestionfruta.models.rutaArchivoTenant)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=120)),
                ('variedad', models.CharField(default='', max_length=120)),
                ('areacultivo', models.CharField(default='', max_length=120)),
                ('produccionmes', models.IntegerField(default=0)),
                ('tipoterreno', models.CharField(default='', max_length=120)),
                ('msnm', models.IntegerField(default=0)),
                ('temperatura', models.IntegerField(default=0)),
                ('imagen', models.ImageField(null=True, upload_to=gestionfruta.models.rutaArchivoTenant)),
            ],
        ),
    ]
