# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfruta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrado',
            name='email',
        ),
        migrations.AddField(
            model_name='registrado',
            name='areacultivo',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='registrado',
            name='msnm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registrado',
            name='produccionmes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registrado',
            name='temperatura',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registrado',
            name='tipoterreno',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='registrado',
            name='variedad',
            field=models.CharField(default='', max_length=120),
        ),
    ]
