# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfruta', '0002_auto_20160524_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrarFinca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('municipio', models.CharField(blank=True, max_length=120, null=True)),
                ('departamento', models.CharField(choices=[('Bogota', 'Bogota'), ('Valle', 'Valle'), ('Antioquia', 'Antioquia'), ('Cauca', 'Cauca'), ('Santander', 'Santander'), ('Guajira', 'Guajira'), ('Amazonas', 'Amazonas'), ('Huila', 'Huila'), ('Putumayo', 'Putumayo')], default='Valle', max_length=1)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Registrado',
            new_name='RegistrarFruta',
        ),
    ]
