# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfruta', '0003_auto_20160628_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrarfinca',
            name='departamento',
            field=models.CharField(choices=[('Bogota', 'Bogota'), ('Valle', 'Valle'), ('Antioquia', 'Antioquia'), ('Cauca', 'Cauca'), ('Santander', 'Santander'), ('Guajira', 'Guajira'), ('Amazonas', 'Amazonas'), ('Huila', 'Huila'), ('Putumayo', 'Putumayo')], default='Valle', max_length=100),
        ),
    ]
