# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfruta', '0004_auto_20160628_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('municipio', models.CharField(blank=True, max_length=120, null=True)),
                ('departamento', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='finca')),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('variedad', models.CharField(default='', max_length=120)),
                ('areacultivo', models.CharField(default='', max_length=120)),
                ('produccionmes', models.IntegerField(default=0)),
                ('tipoterreno', models.CharField(default='', max_length=120)),
                ('msnm', models.IntegerField(default=0)),
                ('temperatura', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='RegistrarFinca',
        ),
        migrations.DeleteModel(
            name='RegistrarFruta',
        ),
    ]
