# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import gestionfruta.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfruta', '0007_remove_fruta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finca',
            name='imagen',
            field=models.ImageField(default='', null=True, upload_to=gestionfruta.models.rutaArchivoTenant),
        ),
        migrations.AlterField(
            model_name='fruta',
            name='imagen',
            field=models.ImageField(null=True, upload_to=gestionfruta.models.rutaArchivoTenant),
        ),
    ]
