# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfruta', '0010_departamento_municipio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='departamento',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
