# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula'), ('NIT', 'NIT'), ('OTHER', 'Otro')], default='CC', max_length=3)),
                ('identificacion', models.CharField(default=0, max_length=100)),
                ('url', models.CharField(default='minFinca', max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='productortenant.Productor'),
        ),
    ]
