# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productortenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productor',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
