# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productortenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productor',
            name='domain_url',
            field=models.CharField(default='miFinca', max_length=100),
        ),
    ]
