# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productortenant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Municipio',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='Departamento',
            new_name='Departament',
        ),
    ]
