INSERT INTO productortenant_departamento (id, nombre) VALUES (1, 'AMAZONAS');
INSERT INTO productortenant_departamento (id, nombre) VALUES (2, 'ANTIOQUIA');
INSERT INTO productortenant_departamento (id, nombre) VALUES (3, 'ARAUCA');
INSERT INTO productortenant_departamento (id, nombre) VALUES (4, 'ATLÁNTICO');
INSERT INTO productortenant_departamento (id, nombre) VALUES (5, 'BOLÍVAR');
INSERT INTO productortenant_departamento (id, nombre) VALUES (6, 'BOYACÁ');
INSERT INTO productortenant_departamento (id, nombre) VALUES (7, 'CALDAS');
INSERT INTO productortenant_departamento (id, nombre) VALUES (8, 'CAQUETÁ');
INSERT INTO productortenant_departamento (id, nombre) VALUES (9, 'CASANARE');
INSERT INTO productortenant_departamento (id, nombre) VALUES (10, 'CAUCA');
INSERT INTO productortenant_departamento (id, nombre) VALUES (11, 'CESAR');
INSERT INTO productortenant_departamento (id, nombre) VALUES (12, 'CHOCÓ');
INSERT INTO productortenant_departamento (id, nombre) VALUES (13, 'CÓRDOBA');
INSERT INTO productortenant_departamento (id, nombre) VALUES (14, 'CUNDINAMARCA');
INSERT INTO productortenant_departamento (id, nombre) VALUES (15, 'GUAINÍA');
INSERT INTO productortenant_departamento (id, nombre) VALUES (16, 'GUAVIARE');
INSERT INTO productortenant_departamento (id, nombre) VALUES (17, 'HUILA');
INSERT INTO productortenant_departamento (id, nombre) VALUES (18, 'LA GUAJIRA');
INSERT INTO productortenant_departamento (id, nombre) VALUES (19, 'MAGDALENA');
INSERT INTO productortenant_departamento (id, nombre) VALUES (20, 'META');
INSERT INTO productortenant_departamento (id, nombre) VALUES (21, 'NARIÑO');
INSERT INTO productortenant_departamento (id, nombre) VALUES (22, 'NORTE DE SANTANDER');
INSERT INTO productortenant_departamento (id, nombre) VALUES (23, 'PUTUMAYO');
INSERT INTO productortenant_departamento (id, nombre) VALUES (24, 'QUINDÍO');
INSERT INTO productortenant_departamento (id, nombre) VALUES (25, 'RISARALDA');
INSERT INTO productortenant_departamento (id, nombre) VALUES (26, 'SAN ANDRÉS Y ROVIDENCIA');
INSERT INTO productortenant_departamento (id, nombre) VALUES (27, 'SANTANDER');
INSERT INTO productortenant_departamento (id, nombre) VALUES (28, 'SUCRE');
INSERT INTO productortenant_departamento (id, nombre) VALUES (29, 'TOLIMA');
INSERT INTO productortenant_departamento (id, nombre) VALUES (30, 'VALLE DEL CAUCA');
INSERT INTO productortenant_departamento (id, nombre) VALUES (31, 'VAUPÉS');
INSERT INTO productortenant_departamento (id, nombre) VALUES (32, 'VICHADA');
